testthat::test_that("sanity checks work", {
  ### sanity checks for getCIforQuantiles()
  ### vecDat
  testthat::expect_error(plotQuantileCIsfromDat(vecDat = "a"))
  testthat::expect_error(plotQuantileCIsfromDat(vecDat = TRUE))
  testthat::expect_error(plotQuantileCIsfromDat(vecDat = 1:5))
  testthat::expect_warning(plotQuantileCIsfromDat(vecDat = 1:24,
                                             vecQuantiles = c(.1, .9),
                                             method = "e",
                                             ci = .95,
                                             R = 9999,
                                             type = 8))
  ### vecQuantiles
  testthat::expect_error(plotQuantileCIsfromDat(vecDat = 1:100, vecQuantiles = "A"))
  testthat::expect_error(plotQuantileCIsfromDat(vecDat = 1:100, vecQuantiles = NA))
  testthat::expect_error(plotQuantileCIsfromDat(vecDat = 1:100, vecQuantiles = -.5))
  testthat::expect_error(plotQuantileCIsfromDat(vecDat = 1:100, vecQuantiles = 1.5))
  ### method
  testthat::expect_error(plotQuantileCIsfromDat(vecDat = 1:100, vecQuantiles = c(.1, .9), method = "sausages"))
  ### ci
  testthat::expect_error(plotQuantileCIsfromDat(vecDat = 1:100, vecQuantiles = c(.1, .9), ci = NA))
  testthat::expect_error(plotQuantileCIsfromDat(vecDat = 1:100, vecQuantiles = c(.1, .9), ci = "A"))
  testthat::expect_error(plotQuantileCIsfromDat(vecDat = 1:100, vecQuantiles = c(.1, .9),ci = c(.5, .9)))
  testthat::expect_error(plotQuantileCIsfromDat(vecDat = 1:100, vecQuantiles = c(.1, .9), ci = 1.5))
  testthat::expect_error(plotQuantileCIsfromDat(vecDat = 1:100, vecQuantiles = c(.1, .9), ci = .5))
  ### bootstrap
  testthat::expect_error(plotQuantileCIsfromDat(vecDat = 1:100, vecQuantiles = c(.1, .9), method = "B", R = "A", type = 8))
  testthat::expect_error(plotQuantileCIsfromDat(vecDat = 1:100, vecQuantiles = c(.1, .9), method = "B", R = NA))
  testthat::expect_error(plotQuantileCIsfromDat(vecDat = 1:100, vecQuantiles = c(.1, .9), method = "B", R = 1:2))
  testthat::expect_error(plotQuantileCIsfromDat(vecDat = 1:100, vecQuantiles = c(.1, .9), method = "B", R = 5))
  testthat::expect_error(plotQuantileCIsfromDat(vecDat = 1:100, vecQuantiles = c(.1, .9), method = "B", R = 50000, type = 8))
  ### type
  testthat::expect_warning(plotQuantileCIsfromDat(vecDat = 1:100, vecQuantiles = c(.1, .9), type = NA))
  testthat::expect_warning(plotQuantileCIsfromDat(vecDat = 1:100, vecQuantiles = c(.1, .9), type = NULL))
  testthat::expect_warning(plotQuantileCIsfromDat(vecDat = 1:100, vecQuantiles = c(.1, .9), type = "A"))
  testthat::expect_warning(plotQuantileCIsfromDat(vecDat = 1:100, vecQuantiles = c(.1, .9), type = 1:2))
  testthat::expect_error(plotQuantileCIsfromDat(vecDat = 1:100, vecQuantiles = c(.1, .9), type = 0))
  testthat::expect_error(plotQuantileCIsfromDat(vecDat = 1:100, vecQuantiles = c(.1, .9), type = 10))
  ### new checks for plotQuantileCIsfromDat
  testthat::expect_error(plotQuantileCIsfromDat(vecDat = 1:100, vecQuantiles = c(.1, .9), method = "N", ci = 0.95, R = 9999, type = 8,
                                                xLab = NA,
                                                yLab = "Probability",
                                                percent = FALSE,
                                                colPoint = "black",
                                                colLCL = "black",
                                                colUCL = "black",
                                                vertQuantiles = TRUE,
                                                vertCLs = FALSE,
                                                shadeCI = TRUE,
                                                addAnnotation = TRUE,
                                                titleText = "ECDF with quantiles and CIs around quantiles",
                                                subtitleText = "",
                                                titleJust = 0.5,
                                                themeBW = TRUE,
                                                printPlot = TRUE,
                                                returnPlot = FALSE))
  testthat::expect_error(plotQuantileCIsfromDat(vecDat = 1:100, vecQuantiles = c(.1, .9), method = "N", ci = 0.95, R = 9999, type = 8,
                                                xLab = LETTERS,
                                                yLab = "Probability",
                                                percent = FALSE,
                                                colPoint = "black",
                                                colLCL = "black",
                                                colUCL = "black",
                                                vertQuantiles = TRUE,
                                                vertCLs = FALSE,
                                                shadeCI = TRUE,
                                                addAnnotation = TRUE,
                                                titleText = "ECDF with quantiles and CIs around quantiles",
                                                subtitleText = "",
                                                titleJust = 0.5,
                                                themeBW = TRUE,
                                                printPlot = TRUE,
                                                returnPlot = FALSE))
  testthat::expect_error(plotQuantileCIsfromDat(vecDat = 1:100, vecQuantiles = c(.1, .9), method = "N", ci = 0.95, R = 9999, type = 8,
                                                xLab = "Value for probability (quantile)",
                                                yLab = NA,
                                                percent = FALSE,
                                                colPoint = "black",
                                                colLCL = "black",
                                                colUCL = "black",
                                                vertQuantiles = TRUE,
                                                vertCLs = FALSE,
                                                shadeCI = TRUE,
                                                addAnnotation = TRUE,
                                                titleText = "ECDF with quantiles and CIs around quantiles",
                                                subtitleText = "",
                                                titleJust = 0.5,
                                                themeBW = TRUE,
                                                printPlot = TRUE,
                                                returnPlot = FALSE))
  testthat::expect_error(plotQuantileCIsfromDat(vecDat = 1:100, vecQuantiles = c(.1, .9), method = "N", ci = 0.95, R = 9999, type = 8,
                                                xLab = "Value for probability (quantile)",
                                                yLab = LETTERS,
                                                percent = FALSE,
                                                colPoint = "black",
                                                colLCL = "black",
                                                colUCL = "black",
                                                vertQuantiles = TRUE,
                                                vertCLs = FALSE,
                                                shadeCI = TRUE,
                                                addAnnotation = TRUE,
                                                titleText = "ECDF with quantiles and CIs around quantiles",
                                                subtitleText = "",
                                                titleJust = 0.5,
                                                themeBW = TRUE,
                                                printPlot = TRUE,
                                                returnPlot = FALSE))
  testthat::expect_error(plotQuantileCIsfromDat(vecDat = 1:100, vecQuantiles = c(.1, .9), method = "N", ci = 0.95, R = 9999, type = 8,
                                                xLab = "Value for probability (quantile)",
                                                yLab = "Probability",
                                                percent = "x",
                                                colPoint = "black",
                                                colLCL = "black",
                                                colUCL = "black",
                                                vertQuantiles = TRUE,
                                                vertCLs = FALSE,
                                                shadeCI = TRUE,
                                                addAnnotation = TRUE,
                                                titleText = "ECDF with quantiles and CIs around quantiles",
                                                subtitleText = "",
                                                titleJust = 0.5,
                                                themeBW = TRUE,
                                                printPlot = TRUE,
                                                returnPlot = FALSE))
  testthat::expect_error(plotQuantileCIsfromDat(vecDat = 1:100, vecQuantiles = c(.1, .9), method = "N", ci = 0.95, R = 9999, type = 8,
                                                xLab = "Value for probability (quantile)",
                                                yLab = "Probability",
                                                percent = NA,
                                                colPoint = "black",
                                                colLCL = "black",
                                                colUCL = "black",
                                                vertQuantiles = TRUE,
                                                vertCLs = FALSE,
                                                shadeCI = TRUE,
                                                addAnnotation = TRUE,
                                                titleText = "ECDF with quantiles and CIs around quantiles",
                                                subtitleText = "",
                                                titleJust = 0.5,
                                                themeBW = TRUE,
                                                printPlot = TRUE,
                                                returnPlot = FALSE))
  testthat::expect_error(plotQuantileCIsfromDat(vecDat = 1:100, vecQuantiles = c(.1, .9), method = "N", ci = 0.95, R = 9999, type = 8,
                                                xLab = "Value for probability (quantile)",
                                                yLab = "Probability",
                                                percent = LETTERS,
                                                colPoint = "black",
                                                colLCL = "black",
                                                colUCL = "black",
                                                vertQuantiles = TRUE,
                                                vertCLs = FALSE,
                                                shadeCI = TRUE,
                                                addAnnotation = TRUE,
                                                titleText = "ECDF with quantiles and CIs around quantiles",
                                                subtitleText = "",
                                                titleJust = 0.5,
                                                themeBW = TRUE,
                                                printPlot = TRUE,
                                                returnPlot = FALSE))
  testthat::expect_error(plotQuantileCIsfromDat(vecDat = 1:100, vecQuantiles = c(.1, .9), method = "N", ci = 0.95, R = 9999, type = 8,
                                                xLab = "Value for probability (quantile)",
                                                yLab = "Probability",
                                                percent = FALSE,
                                                colPoint = NA,
                                                colLCL = "black",
                                                colUCL = "black",
                                                vertQuantiles = TRUE,
                                                vertCLs = FALSE,
                                                shadeCI = TRUE,
                                                addAnnotation = TRUE,
                                                titleText = "ECDF with quantiles and CIs around quantiles",
                                                subtitleText = "",
                                                titleJust = 0.5,
                                                themeBW = TRUE,
                                                printPlot = TRUE,
                                                returnPlot = FALSE))
  testthat::expect_error(plotQuantileCIsfromDat(vecDat = 1:100, vecQuantiles = c(.1, .9), method = "N", ci = 0.95, R = 9999, type = 8,
                                                xLab = "Value for probability (quantile)",
                                                yLab = "Probability",
                                                percent = FALSE,
                                                colPoint = LETTERS,
                                                colLCL = "black",
                                                colUCL = "black",
                                                vertQuantiles = TRUE,
                                                vertCLs = FALSE,
                                                shadeCI = TRUE,
                                                addAnnotation = TRUE,
                                                titleText = "ECDF with quantiles and CIs around quantiles",
                                                subtitleText = "",
                                                titleJust = 0.5,
                                                themeBW = TRUE,
                                                printPlot = TRUE,
                                                returnPlot = FALSE))
  testthat::expect_error(plotQuantileCIsfromDat(vecDat = 1:100, vecQuantiles = c(.1, .9), method = "N", ci = 0.95, R = 9999, type = 8,
                                                xLab = "Value for probability (quantile)",
                                                yLab = "Probability",
                                                percent = FALSE,
                                                colPoint = "black",
                                                colLCL = NA,
                                                colUCL = "black",
                                                vertQuantiles = TRUE,
                                                vertCLs = FALSE,
                                                shadeCI = TRUE,
                                                addAnnotation = TRUE,
                                                titleText = "ECDF with quantiles and CIs around quantiles",
                                                subtitleText = "",
                                                titleJust = 0.5,
                                                themeBW = TRUE,
                                                printPlot = TRUE,
                                                returnPlot = FALSE))
  testthat::expect_error(plotQuantileCIsfromDat(vecDat = 1:100, vecQuantiles = c(.1, .9), method = "N", ci = 0.95, R = 9999, type = 8,
                                                xLab = "Value for probability (quantile)",
                                                yLab = "Probability",
                                                percent = FALSE,
                                                colPoint = "black",
                                                colLCL = LETTERS,
                                                colUCL = "black",
                                                vertQuantiles = TRUE,
                                                vertCLs = FALSE,
                                                shadeCI = TRUE,
                                                addAnnotation = TRUE,
                                                titleText = "ECDF with quantiles and CIs around quantiles",
                                                subtitleText = "",
                                                titleJust = 0.5,
                                                themeBW = TRUE,
                                                printPlot = TRUE,
                                                returnPlot = FALSE))
  testthat::expect_error(plotQuantileCIsfromDat(vecDat = 1:100, vecQuantiles = c(.1, .9), method = "N", ci = 0.95, R = 9999, type = 8,
                                                xLab = "Value for probability (quantile)",
                                                yLab = "Probability",
                                                percent = FALSE,
                                                colPoint = "black",
                                                colLCL = "black",
                                                colUCL = NA,
                                                vertQuantiles = TRUE,
                                                vertCLs = FALSE,
                                                shadeCI = TRUE,
                                                addAnnotation = TRUE,
                                                titleText = "ECDF with quantiles and CIs around quantiles",
                                                subtitleText = "",
                                                titleJust = 0.5,
                                                themeBW = TRUE,
                                                printPlot = TRUE,
                                                returnPlot = FALSE))
  testthat::expect_error(plotQuantileCIsfromDat(vecDat = 1:100, vecQuantiles = c(.1, .9), method = "N", ci = 0.95, R = 9999, type = 8,
                                                xLab = "Value for probability (quantile)",
                                                yLab = "Probability",
                                                percent = FALSE,
                                                colPoint = "black",
                                                colLCL = "black",
                                                colUCL = LETTERS,
                                                vertQuantiles = TRUE,
                                                vertCLs = FALSE,
                                                shadeCI = TRUE,
                                                addAnnotation = TRUE,
                                                titleText = "ECDF with quantiles and CIs around quantiles",
                                                subtitleText = "",
                                                titleJust = 0.5,
                                                themeBW = TRUE,
                                                printPlot = TRUE,
                                                returnPlot = FALSE))
  testthat::expect_error(plotQuantileCIsfromDat(vecDat = 1:100, vecQuantiles = c(.1, .9), method = "N", ci = 0.95, R = 9999, type = 8,
                                                xLab = "Value for probability (quantile)",
                                                yLab = "Probability",
                                                percent = FALSE,
                                                colPoint = "black",
                                                colLCL = "black",
                                                colUCL = "black",
                                                vertQuantiles = NA,
                                                vertCLs = FALSE,
                                                shadeCI = TRUE,
                                                addAnnotation = TRUE,
                                                titleText = "ECDF with quantiles and CIs around quantiles",
                                                subtitleText = "",
                                                titleJust = 0.5,
                                                themeBW = TRUE,
                                                printPlot = TRUE,
                                                returnPlot = FALSE))
  testthat::expect_error(plotQuantileCIsfromDat(vecDat = 1:100, vecQuantiles = c(.1, .9), method = "N", ci = 0.95, R = 9999, type = 8,
                                                xLab = "Value for probability (quantile)",
                                                yLab = "Probability",
                                                percent = FALSE,
                                                colPoint = "black",
                                                colLCL = "black",
                                                colUCL = "black",
                                                vertQuantiles = LETTERS,
                                                vertCLs = FALSE,
                                                shadeCI = TRUE,
                                                addAnnotation = TRUE,
                                                titleText = "ECDF with quantiles and CIs around quantiles",
                                                subtitleText = "",
                                                titleJust = 0.5,
                                                themeBW = TRUE,
                                                printPlot = TRUE,
                                                returnPlot = FALSE))
  testthat::expect_error(plotQuantileCIsfromDat(vecDat = 1:100, vecQuantiles = c(.1, .9), method = "N", ci = 0.95, R = 9999, type = 8,
                                                xLab = "Value for probability (quantile)",
                                                yLab = "Probability",
                                                percent = FALSE,
                                                colPoint = "black",
                                                colLCL = "black",
                                                colUCL = "black",
                                                vertQuantiles = TRUE,
                                                vertCLs = NA,
                                                shadeCI = TRUE,
                                                addAnnotation = TRUE,
                                                titleText = "ECDF with quantiles and CIs around quantiles",
                                                subtitleText = "",
                                                titleJust = 0.5,
                                                themeBW = TRUE,
                                                printPlot = TRUE,
                                                returnPlot = FALSE))
  testthat::expect_error(plotQuantileCIsfromDat(vecDat = 1:100, vecQuantiles = c(.1, .9), method = "N", ci = 0.95, R = 9999, type = 8,
                                                xLab = "Value for probability (quantile)",
                                                yLab = "Probability",
                                                percent = FALSE,
                                                colPoint = "black",
                                                colLCL = "black",
                                                colUCL = "black",
                                                vertQuantiles = TRUE,
                                                vertCLs = LETTERS,
                                                shadeCI = TRUE,
                                                addAnnotation = TRUE,
                                                titleText = "ECDF with quantiles and CIs around quantiles",
                                                subtitleText = "",
                                                titleJust = 0.5,
                                                themeBW = TRUE,
                                                printPlot = TRUE,
                                                returnPlot = FALSE))
  testthat::expect_error(plotQuantileCIsfromDat(vecDat = 1:100, vecQuantiles = c(.1, .9), method = "N", ci = 0.95, R = 9999, type = 8,
                                                xLab = "Value for probability (quantile)",
                                                yLab = "Probability",
                                                percent = FALSE,
                                                colPoint = "black",
                                                colLCL = "black",
                                                colUCL = "black",
                                                vertQuantiles = TRUE,
                                                vertCLs = FALSE,
                                                shadeCI = NA,
                                                addAnnotation = TRUE,
                                                titleText = "ECDF with quantiles and CIs around quantiles",
                                                subtitleText = "",
                                                titleJust = 0.5,
                                                themeBW = TRUE,
                                                printPlot = TRUE,
                                                returnPlot = FALSE))
  testthat::expect_error(plotQuantileCIsfromDat(vecDat = 1:100, vecQuantiles = c(.1, .9), method = "N", ci = 0.95, R = 9999, type = 8,
                                                xLab = "Value for probability (quantile)",
                                                yLab = "Probability",
                                                percent = FALSE,
                                                colPoint = "black",
                                                colLCL = "black",
                                                colUCL = "black",
                                                vertQuantiles = TRUE,
                                                vertCLs = FALSE,
                                                shadeCI = LETTERS,
                                                addAnnotation = TRUE,
                                                titleText = "ECDF with quantiles and CIs around quantiles",
                                                subtitleText = "",
                                                titleJust = 0.5,
                                                themeBW = TRUE,
                                                printPlot = TRUE,
                                                returnPlot = FALSE))
  testthat::expect_error(plotQuantileCIsfromDat(vecDat = 1:100, vecQuantiles = c(.1, .9), method = "N", ci = 0.95, R = 9999, type = 8,
                                                xLab = "Value for probability (quantile)",
                                                yLab = "Probability",
                                                percent = FALSE,
                                                colPoint = "black",
                                                colLCL = "black",
                                                colUCL = "black",
                                                vertQuantiles = TRUE,
                                                vertCLs = FALSE,
                                                shadeCI = TRUE,
                                                addAnnotation = NA,
                                                titleText = "ECDF with quantiles and CIs around quantiles",
                                                subtitleText = "",
                                                titleJust = 0.5,
                                                themeBW = TRUE,
                                                printPlot = TRUE,
                                                returnPlot = FALSE))
  testthat::expect_error(plotQuantileCIsfromDat(vecDat = 1:100, vecQuantiles = c(.1, .9), method = "N", ci = 0.95, R = 9999, type = 8,
                                                xLab = "Value for probability (quantile)",
                                                yLab = "Probability",
                                                percent = FALSE,
                                                colPoint = "black",
                                                colLCL = "black",
                                                colUCL = "black",
                                                vertQuantiles = TRUE,
                                                vertCLs = FALSE,
                                                shadeCI = TRUE,
                                                addAnnotation = LETTERS,
                                                titleText = "ECDF with quantiles and CIs around quantiles",
                                                subtitleText = "",
                                                titleJust = 0.5,
                                                themeBW = TRUE,
                                                printPlot = TRUE,
                                                returnPlot = FALSE))
  testthat::expect_error(plotQuantileCIsfromDat(vecDat = 1:100, vecQuantiles = c(.1, .9), method = "N", ci = 0.95, R = 9999, type = 8,
                                                xLab = "Value for probability (quantile)",
                                                yLab = "Probability",
                                                percent = FALSE,
                                                colPoint = "black",
                                                colLCL = "black",
                                                colUCL = "black",
                                                vertQuantiles = TRUE,
                                                vertCLs = FALSE,
                                                shadeCI = TRUE,
                                                addAnnotation = TRUE,
                                                titleText = 1,
                                                subtitleText = "",
                                                titleJust = 0.5,
                                                themeBW = TRUE,
                                                printPlot = TRUE,
                                                returnPlot = FALSE))
  testthat::expect_error(plotQuantileCIsfromDat(vecDat = 1:100, vecQuantiles = c(.1, .9), method = "N", ci = 0.95, R = 9999, type = 8,
                                                xLab = "Value for probability (quantile)",
                                                yLab = "Probability",
                                                percent = FALSE,
                                                colPoint = "black",
                                                colLCL = "black",
                                                colUCL = "black",
                                                vertQuantiles = TRUE,
                                                vertCLs = FALSE,
                                                shadeCI = TRUE,
                                                addAnnotation = TRUE,
                                                titleText = LETTERS,
                                                subtitleText = "",
                                                titleJust = 0.5,
                                                themeBW = TRUE,
                                                printPlot = TRUE,
                                                returnPlot = FALSE))
  testthat::expect_error(plotQuantileCIsfromDat(vecDat = 1:100, vecQuantiles = c(.1, .9), method = "N", ci = 0.95, R = 9999, type = 8,
                                                xLab = "Value for probability (quantile)",
                                                yLab = "Probability",
                                                percent = FALSE,
                                                colPoint = "black",
                                                colLCL = "black",
                                                colUCL = "black",
                                                vertQuantiles = TRUE,
                                                vertCLs = FALSE,
                                                shadeCI = TRUE,
                                                addAnnotation = TRUE,
                                                titleText = "ECDF with quantiles and CIs around quantiles",
                                                subtitleText = 1,
                                                titleJust = 0.5,
                                                themeBW = TRUE,
                                                printPlot = TRUE,
                                                returnPlot = FALSE))
  testthat::expect_error(plotQuantileCIsfromDat(vecDat = 1:100, vecQuantiles = c(.1, .9), method = "N", ci = 0.95, R = 9999, type = 8,
                                                xLab = "Value for probability (quantile)",
                                                yLab = "Probability",
                                                percent = FALSE,
                                                colPoint = "black",
                                                colLCL = "black",
                                                colUCL = "black",
                                                vertQuantiles = TRUE,
                                                vertCLs = FALSE,
                                                shadeCI = TRUE,
                                                addAnnotation = TRUE,
                                                titleText = "ECDF with quantiles and CIs around quantiles",
                                                subtitleText = LETTERS,
                                                titleJust = 0.5,
                                                themeBW = TRUE,
                                                printPlot = TRUE,
                                                returnPlot = FALSE))
  testthat::expect_error(plotQuantileCIsfromDat(vecDat = 1:100, vecQuantiles = c(.1, .9), method = "N", ci = 0.95, R = 9999, type = 8,
                                                xLab = "Value for probability (quantile)",
                                                yLab = "Probability",
                                                percent = FALSE,
                                                colPoint = "black",
                                                colLCL = "black",
                                                colUCL = "black",
                                                vertQuantiles = TRUE,
                                                vertCLs = FALSE,
                                                shadeCI = TRUE,
                                                addAnnotation = TRUE,
                                                titleText = "ECDF with quantiles and CIs around quantiles",
                                                subtitleText = "",
                                                titleJust = 0.9,
                                                themeBW = TRUE,
                                                printPlot = TRUE,
                                                returnPlot = FALSE))
  testthat::expect_error(plotQuantileCIsfromDat(vecDat = 1:100, vecQuantiles = c(.1, .9), method = "N", ci = 0.95, R = 9999, type = 8,
                                                xLab = "Value for probability (quantile)",
                                                yLab = "Probability",
                                                percent = FALSE,
                                                colPoint = "black",
                                                colLCL = "black",
                                                colUCL = "black",
                                                vertQuantiles = TRUE,
                                                vertCLs = FALSE,
                                                shadeCI = TRUE,
                                                addAnnotation = TRUE,
                                                titleText = "ECDF with quantiles and CIs around quantiles",
                                                subtitleText = "",
                                                titleJust = 0.5,
                                                themeBW = NA,
                                                printPlot = TRUE,
                                                returnPlot = FALSE))
  testthat::expect_error(plotQuantileCIsfromDat(vecDat = 1:100, vecQuantiles = c(.1, .9), method = "N", ci = 0.95, R = 9999, type = 8,
                                                xLab = "Value for probability (quantile)",
                                                yLab = "Probability",
                                                percent = FALSE,
                                                colPoint = "black",
                                                colLCL = "black",
                                                colUCL = "black",
                                                vertQuantiles = TRUE,
                                                vertCLs = FALSE,
                                                shadeCI = TRUE,
                                                addAnnotation = TRUE,
                                                titleText = "ECDF with quantiles and CIs around quantiles",
                                                subtitleText = "",
                                                titleJust = 0.5,
                                                themeBW = LETTERS,
                                                printPlot = TRUE,
                                                returnPlot = FALSE))
  testthat::expect_error(plotQuantileCIsfromDat(vecDat = 1:100, vecQuantiles = c(.1, .9), method = "N", ci = 0.95, R = 9999, type = 8,
                                                xLab = "Value for probability (quantile)",
                                                yLab = "Probability",
                                                percent = FALSE,
                                                colPoint = "black",
                                                colLCL = "black",
                                                colUCL = "black",
                                                vertQuantiles = TRUE,
                                                vertCLs = FALSE,
                                                shadeCI = TRUE,
                                                addAnnotation = TRUE,
                                                titleText = "ECDF with quantiles and CIs around quantiles",
                                                subtitleText = "",
                                                titleJust = 0.5,
                                                themeBW = TRUE,
                                                printPlot = NA,
                                                returnPlot = FALSE))
  testthat::expect_error(plotQuantileCIsfromDat(vecDat = 1:100, vecQuantiles = c(.1, .9), method = "N", ci = 0.95, R = 9999, type = 8,
                                                xLab = "Value for probability (quantile)",
                                                yLab = "Probability",
                                                percent = FALSE,
                                                colPoint = "black",
                                                colLCL = "black",
                                                colUCL = "black",
                                                vertQuantiles = TRUE,
                                                vertCLs = FALSE,
                                                shadeCI = TRUE,
                                                addAnnotation = TRUE,
                                                titleText = "ECDF with quantiles and CIs around quantiles",
                                                subtitleText = "",
                                                titleJust = 0.5,
                                                themeBW = TRUE,
                                                printPlot = LETTERS,
                                                returnPlot = FALSE))
  testthat::expect_error(plotQuantileCIsfromDat(vecDat = 1:100, vecQuantiles = c(.1, .9), method = "N", ci = 0.95, R = 9999, type = 8,
                                                xLab = "Value for probability (quantile)",
                                                yLab = "Probability",
                                                percent = FALSE,
                                                colPoint = "black",
                                                colLCL = "black",
                                                colUCL = "black",
                                                vertQuantiles = TRUE,
                                                vertCLs = FALSE,
                                                shadeCI = TRUE,
                                                addAnnotation = TRUE,
                                                titleText = "ECDF with quantiles and CIs around quantiles",
                                                subtitleText = "",
                                                titleJust = 0.5,
                                                themeBW = TRUE,
                                                printPlot = TRUE,
                                                returnPlot = NA))
  testthat::expect_error(plotQuantileCIsfromDat(vecDat = 1:100, vecQuantiles = c(.1, .9), method = "N", ci = 0.95, R = 9999, type = 8,
                                                xLab = "Value for probability (quantile)",
                                                yLab = "Probability",
                                                percent = FALSE,
                                                colPoint = "black",
                                                colLCL = "black",
                                                colUCL = "black",
                                                vertQuantiles = TRUE,
                                                vertCLs = FALSE,
                                                shadeCI = TRUE,
                                                addAnnotation = TRUE,
                                                titleText = "ECDF with quantiles and CIs around quantiles",
                                                subtitleText = "",
                                                titleJust = 0.5,
                                                themeBW = TRUE,
                                                printPlot = TRUE,
                                                returnPlot = LETTERS))


})


### test comment:
### nothing to say!
